### ISSUE TITLE
Wrong "body" value for certain articles  

### ISSUE THREAD

**Issue by MasterPain111** [EventRegistry/event-registry-python#13]
It seems that the "Body" JSON values are not correct for certain articles. It looks like they are taken from other articles.

Examples are articles with URI 525017041 or 525216702

Regards,
Matt

**Comment by gregorleban** [comment]
True, in case the articles are very short we might incorrectly extract the article body. Our implementation checks for the largest chunks of text in the DOM and can incorrectly identify the article body in some cases. This is something we will look into and try to improve. It is not a common problem, though.
