### ISSUE TITLE
QueryEvent articles filtered by source or QueryArticles filtered by event

### ISSUE THREAD

**Issue by mikestopcontinues** [EventRegistry/event-registry-python#24]
I'm looking to get articles about an event filtered by source, but neither of the python classes seem to allow for it. Is it possibly a hidden api feature? It seems like such a strange omission. Thanks!

**Comment by maggiexyz** [comment]
Mike, there is an example of getting articles by eventUri here: https://github.com/gregorleban/EventRegistry/issues/8 We should be good on that. And QueryEvent does seem to support filter by source. There's an addNewsSource() method.

**Comment by gregorleban** [comment]
This was fixed. It is now possible to also filter articles in an event using various conditions, like keywords, concepts, sources, etc.
