### ISSUE TITLE
Articles Research - In Presence of special characters the title is not complete

### ISSUE THREAD

**Issue by dmarro89** [EventRegistry/event-registry-python#30]
Hi,
when i search Articles often i find not complete titles (like these)
<img width="1656" alt="schermata 2017-03-06 alle 21 10 21" src="https://cloud.githubusercontent.com/assets/13660007/23627526/69900690-02b1-11e7-9730-007fe07fda27.png">

The titles of the articles are:
<img width="731" alt="schermata 2017-03-06 alle 21 12 25" src="https://cloud.githubusercontent.com/assets/13660007/23627616/b8ce00e0-02b1-11e7-8bf2-fcd27c073aa9.png">
<img width="731" alt="schermata 2017-03-06 alle 21 12 37" src="https://cloud.githubusercontent.com/assets/13660007/23627618/ba0e68b4-02b1-11e7-98b7-8f2cb69b5e59.png">

So, in presence of the characters «» the title is cut!

Greetings

**Comment by gregorleban** [comment]
thank you for this info! we've identified the problem and are fixing it.

**Comment by dmarro89** [comment]
Hi @gregorleban,
you expected a timing resolution of the bug?

Thank you
Greetings

**Comment by gregorleban** [comment]
thank you for reminding me - I've just notified our developer again to report on the status of this problem.

**Comment by dmarro89** [comment]
Ok thank you

**Comment by gregorleban** [comment]
this issue should be fixed now. Let us know if you find any more occurrences of this problem.
