### ISSUE TITLE
No results when start/end date specified

### ISSUE THREAD

**Issue by backender** [EventRegistry/event-registry-python#36]
For any constellation of query, whenever I set a start and end date, the api will return: **No results match the search conditions.**
Not only have I tested to query articles which I would receive when I do not set a date but also the given query from the example folder returns no articles:

```
from eventregistry import *
er = EventRegistry()

q = QueryArticles(
    dateStart = datetime.date(2016, 3, 22), dateEnd = datetime.date(2016, 3, 23),
    conceptUri = er.getConceptUri("Brussels"),
    sourceUri = er.getNewsSourceUri("New York Times"))

# return details about the articles, including the concepts, categories, location and image
q.setRequestedResult(RequestArticlesInfo(count = 30,
    returnInfo = ReturnInfo(
        articleInfo = ArticleInfoFlags(duplicateList = True, concepts = True, categories = True, location = True, image = True))))
# execute the query
res = er.execQuery(q)
```

I wonder whether this is a bug and you can reproduce this behaviour?

**Comment by gregorleban** [comment]
As mentioned on the web, terms of service and documentation, the free users are limited only to articles and events from the last month. If this problem occurs only for dates outside of the last month, then that would be the reason for no results.
