### ISSUE TITLE
Can I make a case sensitive keyword query?

### ISSUE THREAD

**Issue by doncat99** [EventRegistry/event-registry-python#37]
```
qStr = ComplexArticleQuery(
        CombinedQuery.AND([
            BaseQuery(dateStart = from_date, dateEnd = till_date),
            BaseQuery(keyword = QueryItems.OR([symbol, name])),
            BaseQuery(categoryUri = QueryItems.OR([businessUri, financeUri])),
            BaseQuery(lang = "eng")
        ])
    )

like if the symbol happen to be "INTL", which is the stock code of Intel Crop., the result articles are not of my interest.

**Comment by gregorleban** [comment]
Hi,
no, all words are normalized when indexed so you cannot make case sensitive keyword query.

**Comment by doncat99** [comment]
Thanks for you reply, @gregorleban.
Then can I make a title field search instead of the whole article field? That would increase the search accuracy as well.

**Comment by gregorleban** [comment]
sorry for the delay in responding to this. The current answer is no, you cannot search specifically in the title, but the next deployment (in about 14 days) will allow also that feature. I was hoping that we'll have this deployment sooner which is also why I was delaying the answer.

**Comment by gregorleban** [comment]
Hi @doncat99 ,

the support for searching in the title, body or both was now added in the latest SDK. Please check the release page for more info: https://github.com/EventRegistry/event-registry-python/releases/tag/6.5.1
