### ISSUE TITLE
List of concepts or categories

### ISSUE THREAD

**Issue by jtan25** [EventRegistry/event-registry-python#40]
Can someone point to where I can see the list of categories/concepts that exist?
I intend to filter my query by categories if possible.
Example: Searching article titles for the word 'obama' yields the article 'Former Michelle Obama chief to head Grammys inclusion group' which is in the business/art_music category. I want to ignore this category if possible.

**Comment by gregorleban** [comment]
Hi,

there are over 5000 categories so we don't have an online list of all of them. You can however download the URIs for all the categories from here:

https://www.dropbox.com/s/dysl0xa3noksk2s/dmoz-categories.txt?dl=0

You should know that the categories are hierarchical - if you, for example, ignore category dmoz/Arts this will also ignore all it's subcategories (i.e. dmoz/Arts/Animation).

Regarding the concepts, we don't have a list of concept URIs. Concepts URIs are URLs of the English Wikipedia. So for example, for Barack Obama, the corresponding URI would be "http://en.wikipedia.org/wiki/Barack_Obama" (notice that we use http://.. and not https://...). 
To get the URIs for the concept given a name, you can also use the autosuggestion methods -
 see here: http://eventregistry.org/documentation?tab=suggConcepts
