### ISSUE TITLE
Wildcard

### ISSUE THREAD

**Issue by JasperHG90** [EventRegistry/event-registry-python#44]
Hello!

I'm trying to figure out if it is possible to query for articles using a wildcard '&ast;' symbol. E.g. if I'm looking for 'fish', 'fishing' and 'fisheries', is there a way to just look for 'fish&ast;'?

Thanks in advance!

Jasper Ginn.

**Comment by gregorleban** [comment]
Hi Jasper,

the wildcard is currently not supported. It is on our todo list but doesn't have a due date yet.

Best,
Gregor

**Comment by JasperHG90** [comment]
Hi Gregor,

Thanks for your fast response. Looking forward to this feature.

Best,

Jasper.
