### ISSUE TITLE
No description returned in concept objects

### ISSUE THREAD

**Issue by leosalt** [EventRegistry/event-registry-python#46]
Concept objects don't contain description property after setting `description = True` in the `ConceptInfoFlags()`.  It doesn't work in the [demo](https://eventregistry.org/documentation) either.

**Comment by gregorleban** [comment]
It's not a bug, but intended behavior. Operations that return articles and events, which each have a long list of concepts, are not returning concept descriptions. Descriptions could be rather long and this would significantly increase the output size.
