### ISSUE TITLE
Get articles for topic page always has empty array for authors

### ISSUE THREAD

**Issue by joelhulen** [EventRegistry/event-registry-python#59]
Using the `TopicPage.getArticles` method in the SDK, the `authors` array is always empty, despite which `ArticleInfoFlags` I define. Here's an example:

```
t.getArticles(page = 1,
            sortBy="date",
            returnInfo=ReturnInfo(
                articleInfo = ArticleInfoFlags(
                    concepts=False,
                    categories=False,
                    eventUri=False,
                    title=False,
                    basicInfo=False,
                    body=False,
                    url=True,
                    authors=True,
                    image=False,
                    sentiment=False,
                    bodyLen=0
                )
        ))
```

I see the same thing happening on the "search articles for topic" sandbox page: https://eventregistry.org/documentation/sandbox?tab=searchArticlesForTopic

Is this omission by design or is there a flaw in the service that returns the article data for topic pages? If we cannot retrieve the authors using this endpoint, we'll need to go back and make additional API calls through another endpoint to retrieve that data.

**Comment by gregorleban** [comment]
Hi, 

I don't think there is a problem with the query or the SDK. Maybe you are simply retrieving articles that don't have authors specified or at least we weren't able to extract them. This is a simple query that for me returns authors for several articles:
```
er = EventRegistry()

t = TopicPage(er)
t.addSource("dailyherald.com", 50)
x = t.getArticles()
for art in x.get("articles", {}).get("results", []):
    print(art.get("authors"))
```

If you have a source or an article that has clearly specified authors that we don't extract, you can let us know and we can check if the extraction can be improved. In general we try to extract authors from several properties in the articles, but not necessarily from all of them.
