### ISSUE TITLE
Porn Article into results 

### ISSUE THREAD

**Issue by stride-srl** [EventRegistry/event-registry-python#62]
Trying to call up any article search may, at certain times of the day, return several (many) porn articles. Despite the introduction of 'ignoreSourceUri' or 'ignoreSourceGroupUri', no changes are noticeable:

Call:
`https://newsapi.ai/api/v1/article/getArticles`

Body of call

`{
    "query": {
        "$query": {
            "$and": [
                {
                    "keyword": "ciao"
                },
                {
                    "lang": "ita",
                    "ignoreSourceUri": [
                        "fap-cat.com","ice-porn-casting.net"
                    ]
                }
            ]
        },
        "$filter": {
            "isDuplicate": "skipDuplicates"
        }
    },
    "action": "getArticles",
    "articlesPage": 1,
    "articlesCount": 100,
    "articlesSortBy": "date",
    "articlesSortByAsc": false,
    "articlesArticleBodyLen": -1,
    "resultType": "articles",
    "apiKey": "xxxxxxxx",
    "forceMaxDataTimeWindow": 31,
    "includeArticleCategories": "true",
    "includeArticleConcepts": "true"
}`

Result : 
` .......,{
                "uri": "7749244783",
                "lang": "ita",
                "isDuplicate": false,
                "date": "2023-09-24",
                "time": "12:40:07",
                "dateTime": "2023-09-24T12:40:07Z",
                "dateTimePub": "2023-09-24T11:48:53Z",
                "dataType": "news",
                "sim": 0,
                "url": "https://ice-porn-casting.net/ice-porn-casting-net/video-porno/Mamme%20scopate%20oltre%20al%20figlio",
                "title": "*** scopate oltre al figlio",
                 ..... },
       `

**Comment by gregorleban** [comment]
To specify a list of sources to ignore, you have to specify them like this:
```
{
    "query": {
        "$query": {
            "$and": [
                {
                    "keyword": "ciao"
                },
                {
                    "lang": "ita"
                }
            ],
            "$not": {
                "sourceUri": {
                    "$or": [
                        "fap-cat.com",
                        "ice-porn-casting.net"
                    ]
                }
            }
        },
        "$filter": {
            "isDuplicate": "skipDuplicates"
        }
    },
    "action": "getArticles",
    "articlesPage": 1,
    "articlesCount": 100,
    "articlesSortBy": "date",
    "articlesSortByAsc": false,
    "articlesArticleBodyLen": -1,
    "resultType": "articles",
    "forceMaxDataTimeWindow": 31,
    "includeArticleCategories": "true",
    "includeArticleConcepts": "true",
    "apiKey": "{{ _.prodApiKey }}"
}
```
see documentation at: https://github.com/EventRegistry/event-registry-python/wiki/Searching-for-articles#advanced-query-language

**Comment by stride-srl** [comment]
Thanks so much, it's working
