### ISSUE TITLE
False "You have used all available tokens..." error message

### ISSUE THREAD

**Issue by mananbhalodia** [EventRegistry/event-registry-python#65]
Hello, I seem to be getting the error mentioned above however I have not hit the limit for the free account, I am well bellow around 47 tokens used this month.

This is the stack trace -
`
DEFAULT 2023-12-27T06:13:14.510540Z for article in q.execQuery(er, sortBy="socialScore", maxItems=50): DEFAULT 2023-12-27T06:13:14.510545Z File "/layers/google.python.pip/pip/lib/python3.11/site-packages/eventregistry/QueryArticles.py", line 394, in __next__ DEFAULT 2023-12-27T06:13:14.510549Z self._getNextArticleBatch() DEFAULT 2023-12-27T06:13:14.510555Z File "/layers/google.python.pip/pip/lib/python3.11/site-packages/eventregistry/QueryArticles.py", line 374, in _getNextArticleBatch DEFAULT 2023-12-27T06:13:14.510559Z res = self._er.execQuery(self) DEFAULT 2023-12-27T06:13:14.510564Z ^^^^^^^^^^^^^^^^^^^^^^^^ DEFAULT 2023-12-27T06:13:14.510569Z File "/layers/google.python.pip/pip/lib/python3.11/site-packages/eventregistry/EventRegistry.py", line 221, in execQuery DEFAULT 2023-12-27T06:13:14.510574Z respInfo = self.jsonRequest(query._getPath(), allParams, allowUseOfArchive = allowUseOfArchive) DEFAULT 2023-12-27T06:13:14.510578Z ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ DEFAULT 2023-12-27T06:13:14.510584Z File "/layers/google.python.pip/pip/lib/python3.11/site-packages/eventregistry/EventRegistry.py", line 302, in jsonRequest DEFAULT 2023-12-27T06:13:14.510589Z raise self._lastException or Exception("No valid return data provided") DEFAULT 2023-12-27T06:13:14.510594Z File "/layers/google.python.pip/pip/lib/python3.11/site-packages/eventregistry/EventRegistry.py", line 278, in jsonRequest DEFAULT 2023-12-27T06:13:14.510597Z raise Exception(respInfo.text) DEFAULT 2023-12-27T06:13:15.553164Z Exception: You have used all available tokens for unsubscribed users from this IP address. In order to continue using Event Registry please subscribe to a paid plan.
`

This only happens when I run the code through Google Cloud Functions; when I run locally I am able to hit the API just fine.

**Comment by gregorleban** [comment]
This is not an error - please read the message returned: You have used all available tokens for unsubscribed users from this IP address. In order to continue using Event Registry please subscribe to a paid plan

For free users we don't monitor just the user account but also the IP address from where the requests are made. When you are using the IP addresses from where many users already created requests, your requests will be rejected. You either have to use a different IP address when making the requests or subscribe to a paid plan.
